// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace POETheRideYouRent.Models
{
    public partial class CarMake
    {
        public int CarMakeId { get; set; }
        public string MakeDescription { get; set; }
    }
}