// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cldv6211TheRideYouRent.Models
{
    public partial class CarBodyType
    {
        public int CarBodyTypeId { get; set; }
        public string BodyTypeDescription { get; set; }
    }
}