// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cldv6211TheRideYouRent.Models
{
    public partial class Rental
    {
        public Rental()
        {
            ReturnCar = new HashSet<ReturnCar>();
        }

        public string RentalNo { get; set; }
        public decimal RentalFee { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public string CarNo { get; set; }
        public string InspectorNo { get; set; }
        public string DriverId { get; set; }

        public virtual Car CarNoNavigation { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Inspector InspectorNoNavigation { get; set; }
        public virtual ICollection<ReturnCar> ReturnCar { get; set; }
    }
}