// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace cldv6211TheRideYouRent.Models
{
    public partial class ReturnCar
    {
        public string ReturnId { get; set; }
        public string RentalNo { get; set; }
        public string InspectorNo { get; set; }
        public DateTime ReturnDate { get; set; }
        public int ElapsedDate { get; set; }
        public double? Fine { get; set; }

        public virtual Inspector InspectorNoNavigation { get; set; }
        public virtual Rental RentalNoNavigation { get; set; }
    }
}