// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TheRideYouRentFinal.Models
{
    public partial class Driver
    {
        public Driver()
        {
            Rental = new HashSet<Rental>();
        }

        public string DriverId { get; set; }
        public string DriverName { get; set; }
        public string DriverAddress { get; set; }
        public string DriverEmail { get; set; }
        public string DriverContactNumber { get; set; }

        public virtual ICollection<Rental> Rental { get; set; }
    }
}